/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ElLayout {
        "center": boolean;
        "margin": 'auto' | 'none';
        "middle": boolean;
    }
    interface ElToast {
        "fadeDuration"?: number;
        "open": () => Promise<void>;
        "opened"?: boolean;
        "positionRight"?: number;
        "positionTop"?: number;
        "size"?: 'small' | 'default' | 'large';
        "variant"?: 'primary' | 'secondary' | 'tertiary';
    }
}
export interface ElToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElToastElement;
}
declare global {
    interface HTMLElLayoutElement extends Components.ElLayout, HTMLStencilElement {
    }
    var HTMLElLayoutElement: {
        prototype: HTMLElLayoutElement;
        new (): HTMLElLayoutElement;
    };
    interface HTMLElToastElement extends Components.ElToast, HTMLStencilElement {
    }
    var HTMLElToastElement: {
        prototype: HTMLElToastElement;
        new (): HTMLElToastElement;
    };
    interface HTMLElementTagNameMap {
        "el-layout": HTMLElLayoutElement;
        "el-toast": HTMLElToastElement;
    }
}
declare namespace LocalJSX {
    interface ElLayout {
        "center"?: boolean;
        "margin"?: 'auto' | 'none';
        "middle"?: boolean;
    }
    interface ElToast {
        "fadeDuration"?: number;
        "onEl-toast-closed"?: (event: ElToastCustomEvent<void>) => void;
        "opened"?: boolean;
        "positionRight"?: number;
        "positionTop"?: number;
        "size"?: 'small' | 'default' | 'large';
        "variant"?: 'primary' | 'secondary' | 'tertiary';
    }
    interface IntrinsicElements {
        "el-layout": ElLayout;
        "el-toast": ElToast;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "el-layout": LocalJSX.ElLayout & JSXBase.HTMLAttributes<HTMLElLayoutElement>;
            "el-toast": LocalJSX.ElToast & JSXBase.HTMLAttributes<HTMLElToastElement>;
        }
    }
}
